name: lint&test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - "starter/frontend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: 'starter/frontend'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './starter/frontend/package-lock.json'
    - run: npm ci
    - run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: 'starter/frontend'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './starter/frontend/package-lock.json'
    - run: npm ci
    - run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: 'starter/frontend'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './starter/frontend/package-lock.json'
    - run: npm run build
